### ISSUE TITLE
Feature: How we can get Shaver files (.json) ?

### ISSUE THREAD

**Issue by nmjay** [Autodesk-Forge/viewer-javascript-offline.sample#1]
Normal: We create new bucket and upload file to Autodesk Server. How we can get Shaver file and run offine in our server ?

**Comment by shiya** [comment]
We wrote two samples, one in [Node.js](https://github.com/cyrillef/extract-view.and.data.api) and one in [PHP](https://github.com/cyrillef/extract-php-view.and.data.api) that you can use to download. Basically call the [Items API](https://developer.autodesk.com/api/view-and-data-api/) and download the viewables.
