### ISSUE TITLE
Doesn't work locally

### ISSUE THREAD

**Issue by SelaOAL** [Autodesk-Forge/viewer-javascript-offline.sample#4]
I download the repo and click the html file but nothing comes up.
I also tried to run it in incognito but it didn't help...

Also, if I want to change the model, do I need the whole bubbles or a translated svf file is enough?

**Comment by shiya** [comment]
WebGL assets needs to be loaded with a server. If you have python 2.x on your machine you can use `python -m SimpleHTTPServer` to serve up the index.html.

**Comment by SelaOAL** [comment]
Is there something that can be done with node.js?

**Comment by shiya** [comment]
Yep, from [this node package](https://www.npmjs.com/package/http-server)
Do a install `npm install http-server -g`
Then just type `http-server`

**Comment by SelaOAL** [comment]
Ok this works.
Is it possible to make it happen from the browser?

**Comment by shiya** [comment]
AFAIK, no.
