### ISSUE TITLE
The 'view and data; part of the repo readme title should say 'Forge Viewer', shouldn't it?

### ISSUE THREAD

**Issue by jeremytammik** [Autodesk-Forge/viewer-javascript-offline.sample#6]

**Comment by shiya** [comment]
https://github.com/Developer-Autodesk/viewer-javascript-offline.sample/commit/56029f7ef65bc2247776bdfb1aed7f97cca8f177
You have write access to this repo too, @jeremytammik  :)

**Comment by jeremytammik** [comment]
i thought i might and did not want to mess it up for you without asking permission  :-)
