### ISSUE TITLE
Convert  to svf

### ISSUE THREAD

**Issue by mbow1** [Autodesk-Forge/viewer-javascript-offline.sample#9]
Hello
I just have a question.
in "viewer-javascript-offline.sample" the 3D file is in ".svf" I would like to know how to convert or export a Revit or ifc file in svf
thank you in advance

**Comment by xavier-atero** [comment]
You can try Autodesk Forge Viewer - Model Extractor: https://extract.autodesk.io/

**Comment by cyrillef** [comment]
Hi, extract.autodesk.io is sample which shows you to translate an Revit or IFC file to SVF, and then download the svf file locally. But what you want is look at [this API](https://forge.autodesk.com/en/docs/model-derivative/v2/reference/http/job-POST/) where the translation is done.
